<?xml version="1.0"?>
<package format="2">
  <name>my_car</name>
  <version>0.0.1</version>
  <description>Differential drive car URDF model for ROS Noetic</description>
  <maintainer email="you@example.com">eeexty</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>urdf</exec_depend>
</package>
