<?xml version="1.0"?>
<package format="2">
  <name>smartcar_control</name>
  <version>0.1.0</version>
  <description>阿克曼四轮小车的键盘遥控节点与前轮 TF 补全节点</description>

  <maintainer email="hr0622@users.noreply.github.com">hr0622</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
</package>
